<?php

/**
 * @Entity("category")
 */
class Category extends Model
{

	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Name;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Slug;

	public static function deleteAll($ids)
	{
		$db = Database::factory();
		
		$list = '(';
		foreach ($ids as $k => $i)
		{
			$list .= "?,";
			$ids[$k] = (int) $i;
		}
		$list = substr($list, 0, strlen($list) - 1) . ')';
		
		$db->Category->whereArray('Id IN ' . $list, $ids)->deleteAll();
		$db->save();
	}

}