<?php

/**
 * @Entity("category")
 */
class Category extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Name;
	
	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Slug;
}