<?php

/**
 * @Entity("page")
 */
class Page extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="String")
	 */
	public $Title;
	
	/**
	 * @Column(Type="String")
	 */
	public $Slug;
	
	/**
	 * @Column(Type="String")
	 */
	public $Content;
	
	/**
	 * @Column(Type="Int")
	 */
	public $ParentId;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Status;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Order;
	
	public static function deleteAll($ids)
	{
		$db = Database::factory();
		
		$list = '(';
		foreach ($ids as $k => $i)
		{
			$list .= '?,';
			$ids[$k] = (int)$i;
		}
		$list = substr($list, 0, strlen($list) - 1) . ')';
		
		$db->Page->whereArray('Id IN ' . $list, $ids)->deleteAll();
		$db->save();
	}
}