<?php

/**
 * @Entity("page")
 */
class Page extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="String")
	 */
	public $Title;
	
	/**
	 * @Column(Type="String")
	 */
	public $Slug;
	
	/**
	 * @Column(Type="String")
	 */
	public $Content;
	
	/**
	 * @Column(Type="Int")
	 */
	public $ParentId;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Status;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Order;
}