<?php

/**
 * @Entity("post")
 */
class Post extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="String")
	 */
	public $Title;
	
	/**
	 * @Column(Type="String")
	 */
	public $Slug;
	
	/**
	 * @Column(Type="Int")
	 */
	public $CreatedDate;
	
		/**
	 * @Column(Type="Int")
	 */
	public $PublicatedDate;
	
	/**
	 * @Column(Type="Int")
	 */
	public $UpdatedDate;
	
	/**
	 * @Column(Type="Int")
	 */
	public $UserId;
	
	/**
	 * @Column(Type="String")
	 */
	public $Content;
	
	/**
	 * @Column(Type="Int")
	 */
	public $Status;
	
	/**
	 * Retorna as categorias de um post.
	 * @param int		$p	Pagina de resultados
	 * @param int		$m	Quantidade máxima de resultados retornados
	 * @param string	$o	Coluna para ordenação
	 * @param string	$t	Tipo da ordenação
	 * @return array		Array contendo as categorias desejadas
	 */
	public function getCategories($p = 1, $m = 10, $o = 'Id', $t = 'DESC')
	{
		return ViewCategory::allByPost($this->Id, $p, $m, $o, $t);
	}
	
	/**
	 * Retorna um post pelo slug.
	 * @param	string	$slug	Slug do post retornado.
	 * @return	mixed			resultado encontrado.
	 */
	public static function getBySlug($slug)
	{
		$db = Database::factory();
		return $db->Post->single('Slug = ?', $slug);
	}
}