<?php

/**
 * @Entity("user")
 */
class User extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;
	
	/**
	 * @Column(Type="String")
	 */
	public $Name;
	
	/**
	 * @Column(Type="String")
	 */
	public $Email;
	
	/**
	 * @Column(Type="String")
	 */
	public $Password;
	
	public static function login($email, $password)
	{
		$db = Database::factory();
		return $db->User->single('Email = ? AND Password = ?', $email, md5($password));
	}
}